language: python
dist: bionic
addons:
  apt:
    packages:
    - openjdk-8-jdk
cache:
  pip: true
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - mkdir -p /opt
  - wget -q -O /opt/spark.tgz https://archive.apache.org/dist/spark/spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz
  - tar xzf /opt/spark.tgz -C /opt/
  - rm /opt/spark.tgz
  - export SPARK_HOME=/opt/spark-2.4.7-bin-hadoop2.7
  - export PATH=$PATH:/opt/spark-2.4.7-bin-hadoop2.7/bin
  - ls -l /usr/lib/jvm
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  - export PATH=$JAVA_HOME/bin:$PATH
  - java -version
  - pip install -r test-requirements.txt
  - pip install pyspark==2.4.7
  - pip install pytest-spark==0.4.5
script:
  - python -m pytest
