# This workflow runs edgetest on datacompy @ 17:30 UTC Fridays.
# https://github.com/edgetest-dev/run-edgetest-action

name: Run edgetest
on:
  schedule:
    - cron: '30 17 * * 5'
  workflow_dispatch:  # allows manual dispatch
jobs:
  edgetest:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    name: running edgetest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Python 3.12
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5  # v4.0.1
        with:
          auto-update-conda: true
          python-version: '3.12'
          channels: conda-forge

      - name: Setup Java JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287  # v5.3.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install edgetest
        shell: bash -el {0}
        run: |
          conda install pip
          conda install edgetest edgetest-conda
          python -m pip install ."[spark, qa, tests, tests-spark]"

      - name: Run edgetest
        shell: bash -el {0}
        run: |
          edgetest -c pyproject.toml --export

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1  # v8.1.1
        with:
          branch: edgetest-patch
          base: ${{ github.ref_name }}
          delete-branch: true
          title: Changes by run-edgetest action
          commit-message: '[edgetest] automated change'
          body: Automated changes by [run-edgetest-action](https://github.com/edgetest-dev/run-edgetest-action) GitHub action
          add-paths: |
            pyproject.toml
