# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  build:

    runs-on: ubuntu-latest 
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10']
        spark-version: [3.0.3, 3.1.2, 3.2.0]
        hadoop: [3.2]
        include:
          - python-version: 3.6
            spark-version: 2.4.8
            hadoop: 2.7
          - python-version: 3.7
            spark-version: 2.4.8
            hadoop: 2.7
    env:
      PYTHON_VERSION: ${{ matrix.python-version }} 
      SPARK_VERSION: ${{ matrix.spark-version }}

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3 
      with:
        java-version: 1.8
        
    - name: Install Spark
      run: |
        wget -q -O spark.tgz https://archive.apache.org/dist/spark/spark-${{ matrix.spark-version }}/spark-${{ matrix.spark-version }}-bin-hadoop${{ matrix.hadoop }}.tgz
        tar xzf spark.tgz
        rm spark.tgz
        echo "SPARK_HOME=${{ runner.workspace }}/datacompy/spark-${{ matrix.spark-version }}-bin-hadoop${{ matrix.hadoop }}" >> $GITHUB_ENV
        echo "${{ runner.workspace }}/datacompy/spark-${{ matrix.spark-version }}-bin-hadoop${{ matrix.hadoop }}/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-spark pypandoc
        python -m pip install pyspark==${{ matrix.spark-version }}
        python -m pip install .[dev,spark]
    
    - name: Test with pytest
      run: |
        python -m pytest tests/
